name: CI

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        BUILDMODE: [CIBUILDWHEEL, ASTROPY]
        
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        if: ${{ matrix.os == 'ubuntu-latest' }}
        id: qemu
        uses: docker/setup-qemu-action@v1

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.2.2

      - name: Set BUILDMODE
        run: |
          if [ "CIBUILDWHEEL" == "${{ matrix.BUILDMODE }}" ]; then
            echo "BUILDMODE=CIBUILDWHEEL" >> $GITHUB_ENV;
          else
            echo "BUILDMODE=ASTROPY" >> $GITHUB_ENV;
          fi

      - name: Set global variables
        run: |
          echo "NUMPY_VERSION=stable" >> $GITHUB_ENV;
          echo "MAIN_CMD='python setup.py'" >> $GITHUB_ENV;
          echo "CONDA_DEPENDENCIES='sphinx pillow coveralls coverage pytest'" >> $GITHUB_ENV;
          echo "SETUP_XVFB=False" >> $GITHUB_ENV;
          echo "EVENT_TYPE=push pull_request" >> $GITHUB_ENV;
          echo "SETUP_CMD=test" >> $GITHUB_ENV;
          echo "CONDA_CHANNELS=conda-forge" >> $GITHUB_ENV;
          echo "CONDA_CHANNEL_PRIORITY=True" >> $GITHUB_ENV;
          echo "TWINE_USERNAME=dhoese" >> $GITHUB_ENV;
          echo "CIBW_TEST_COMMAND=python {project}/selftest.py" >> $GITHUB_ENV;
          echo "CIBW_BEFORE_BUILD_LINUX=yum install -y freetype-devel" >> $GITHUB_ENV;
          #echo "CIBW_BEFORE_TEST=yum update && yum install -y libjpeg-devel" >> $GITHUB_ENV;
          echo "CIBW_SKIP=cp34-* cp35-* pp27-* pp36-* pp37-* pp38-* *-musllinux_*" >> $GITHUB_ENV;
          echo "CIBW_TEST_REQUIRES=numpy pillow pytest" >> $GITHUB_ENV;
          echo "CIBW_ARCHS_LINUX=auto aarch64" >> $GITHUB_ENV;

      - name: Run install script
        run: source ci/travis-install.sh

      - name: Run a build script
        run: ci/travis-build.sh
